version: '3'

services:
  db:
    image: mysql:8.4.4
    container_name: urly-db
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: urly
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: h22122002h
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - urly-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: urly-backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - urly-network
    depends_on:
      db:
        condition: service_healthy

networks:
  urly-network:
    driver: bridge